/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioTest: typeof import('./src/components/AudioTest.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    BsCardText: typeof import('@kalimahapps/vue-icons/bs')['BsCardText']
    BxImage: typeof import('@kalimahapps/vue-icons/bx')['BxImage']
    CgPlayButtonR: typeof import('@kalimahapps/vue-icons/cg')['CgPlayButtonR']
    ChRefresh: typeof import('@kalimahapps/vue-icons/ch')['ChRefresh']
    EditAudioComponent: typeof import('./src/components/EditAudioComponent.vue')['default']
    EditImageComponent: typeof import('./src/components/EditImageComponent.vue')['default']
    EditMultiselectComponent: typeof import('./src/components/EditMultiselectComponent.vue')['default']
    EditTextComponent: typeof import('./src/components/EditTextComponent.vue')['default']
    FaBackward: typeof import('@kalimahapps/vue-icons/fa')['FaBackward']
    FaCompress: typeof import('@kalimahapps/vue-icons/fa')['FaCompress']
    FaExpand: typeof import('@kalimahapps/vue-icons/fa')['FaExpand']
    FaForward: typeof import('@kalimahapps/vue-icons/fa')['FaForward']
    FaGears: typeof import('@kalimahapps/vue-icons/fa')['FaGears']
    FaHouse: typeof import('@kalimahapps/vue-icons/fa')['FaHouse']
    FaPenToSquare: typeof import('@kalimahapps/vue-icons/fa')['FaPenToSquare']
    FaUser: typeof import('@kalimahapps/vue-icons/fa')['FaUser']
    FaVolumeHigh: typeof import('@kalimahapps/vue-icons/fa')['FaVolumeHigh']
    FaWandMagicSparkles: typeof import('@kalimahapps/vue-icons/fa')['FaWandMagicSparkles']
    FeCameraOff: typeof import('@kalimahapps/vue-icons/fe')['FeCameraOff']
    Modal: typeof import('./src/components/Modal.vue')['default']
    PWABadge: typeof import('./src/components/PWABadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
