/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerOneByOneMathDatabaseItemDataInterface {
  firstNumber: number;
  secondNumber: number;
  options: string;
  sound: string;
  audioType: number;
  successSound: string;
  successSoundType: number;
  successImage: string;
  successImageType: number;
  successAnimations: string;
  successImageTime: number;
  
}
