/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerAppInterface {
  email: string;
  name: string;
  uniqueName: string;
  version: number;
  touched: boolean;
  lastModified: number;
  homePageImageType: number;
  homePageImage: string;
  authenticationType: string;
  lang: string;
  enableNarrator: boolean;
  groups: string;
  id: string;
  lastSync: number;
  
}
