/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerFollowerRequestInterface {
  leaderAppId: string;
  followerAppId: string;
  id: string;
  followerName: string;
  leaderName: string;
  followerEmail: string;
  leaderEmail: string;
  initiatedByFollower: boolean;
  lastModified: number;
  touched: boolean;
  version: number;
  status: number;
  groups: string;
  points: number;
  completionLastModified: number;
  
}
