/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerRouterInterface {
  id: string;
  appId: string;
  routerMac: string;
  ipAddress: string;
  mondayTimesAndDurations: string;
  tuesdayTimesAndDurations: string;
  wednesdayTimesAndDurations: string;
  thursdayTimesAndDurations: string;
  fridayTimesAndDurations: string;
  saturdayTimesAndDurations: string;
  sundayTimesAndDurations: string;
  version: number;
  lastModified: number;
  touched: boolean;
  status: number;
  
}
