/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerSpellingDatabaseItemInterface {
  data: SpellingDatabaseItemData;
  itemType: number;
  order: number;
  unitId: string;
  appId: string;
  lastModified: number;
  version: number;
  databaseId: string;
  id: string;
  dataText: string;
  
}
export interface SpellingDatabaseItemData {
  letters: string;
  image: string;
  sound: string;
  text: string;
  imageType: number;
  visualHint: string;
  audioType: number;
  successSound: string;
  successSoundType: number;
  successImage: string;
  successImageType: number;
  successAnimations: string;
  successImageTime: number;
  
}
