/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerSyncRequestInterface {
  app?: App;
  database?: Database;
  databaseUnit?: DatabaseUnit;
  databaseItem?: DatabaseItem;
  followerRequest?: FollowerRequest;
  followerDatabase?: FollowerDatabase;
  router?: Router;
  followerDatabaseCompletion?: FollowerDatabaseCompletion;
  media?: Media;
  deletion?: Deletion;
  
}
export interface App {
  email: string;
  name: string;
  uniqueName: string;
  version: number;
  lastModified: number;
  homePageImageType: number;
  homePageImage: string;
  authenticationType: string;
  lang: string;
  enableNarrator: boolean;
  groups: string;
  id: string;
  
}
export interface Database {
  name: string;
  lastModified: number;
  version: number;
  appId: string;
  id: string;
  order: number;
  homePageIconType: number;
  homePageIcon: string;
  
}
export interface DatabaseUnit {
  name: string;
  order: number;
  lastModified: number;
  version: number;
  id: string;
  appId: string;
  databaseId: string;
  successVideoType: number;
  successVideoUrl: string;
  successAnimations: string;
  successSound: string;
  successSoundType: number;
  homePageImageType: number;
  homePageImage: string;
  router: string;
  routerTime: number;
  routerTimeImmediate: boolean;
  points: number;
  
}
export interface DatabaseItem {
  itemType: number;
  order: number;
  unitId: string;
  appId: string;
  lastModified: number;
  version: number;
  databaseId: string;
  id: string;
  dataText: string;
  data: unknown;
  
}
export interface FollowerRequest {
  leaderAppId: string;
  followerAppId: string;
  id: string;
  followerName: string;
  leaderName: string;
  followerEmail: string;
  leaderEmail: string;
  initiatedByFollower: boolean;
  lastModified: number;
  version: number;
  status: number;
  groups: string;
  points: number;
  
}
export interface FollowerDatabase {
  followerRequestId: string;
  id: string;
  databaseId: string;
  lastModified: number;
  version: number;
  
}
export interface Router {
  id: string;
  appId: string;
  routerMac: string;
  ipAddress: string;
  mondayTimesAndDurations: string;
  tuesdayTimesAndDurations: string;
  wednesdayTimesAndDurations: string;
  thursdayTimesAndDurations: string;
  fridayTimesAndDurations: string;
  saturdayTimesAndDurations: string;
  sundayTimesAndDurations: string;
  version: number;
  lastModified: number;
  status: number;
  
}
export interface FollowerDatabaseCompletion {
  id: string;
  followerRequestId: string;
  description: string;
  itemId: string;
  parentItemId: string;
  itemLevel: number;
  lastModified: number;
  version: number;
  
}
export interface Media {
  id: string;
  size: number;
  data: string;
  appId: string;
  lastModified: number;
  
}
export interface Deletion {
  id: string;
  level: number;
  
}
