/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerDatabaseInterface {
  name: string;
  lastModified: number;
  version: number;
  appId: string;
  id: string;
  order: number;
  homePageIconType: number;
  homePageIcon: string;
  touched: boolean;
  unitLastModified: number;
  itemLastModified: number;
  mediaLastModified: number;
  
}
