/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerDatabaseUnitInterface {
  name: string;
  order: number;
  lastModified: number;
  touched: boolean;
  version: number;
  id: string;
  appId: string;
  databaseId: string;
  successVideoType: number;
  successVideoUrl: string;
  successAnimations: string;
  successSound: string;
  successSoundType: number;
  homePageImageType: number;
  homePageImage: string;
  router: string;
  routerTime: number;
  routerTimeImmediate: boolean;
  points: number;
  
}
