/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServerOneByTwoDigraphsDatabaseItemDataInterface {
  leftDigraphs: string;
  rightDigraphs: string;
  image: string;
  sound: string;
  text: string;
  imageType: number;
  visualHint: string;
  audioType: number;
  successSound: string;
  successSoundType: number;
  successImage: string;
  successImageType: number;
  successAnimations: string;
  successImageTime: number;
  
}
