import { ResourceValue } from "./ResourceValue";
import { GlobalResources } from "./GlobalResources";

const resourcesInternal =
{
  Sync: new ResourceValue('Sync'),
  You_need_to_login_to_access_$needle$: new ResourceValue('You need to login to access {needle}'),
  You_need_to_login_to_access_this_page: new ResourceValue('You need to login to access this page'),
  App_missing_from_request: new ResourceValue('App missing from request'),
  Completed: new ResourceValue('Completed'),
  Unit_2: new ResourceValue('Unit 2'),
  Unit_3: new ResourceValue('Unit 3'),
  Unit_4: new ResourceValue('Unit 4'),
  Public_App: new ResourceValue('Public App'),
  Public: new ResourceValue('Public'),
  Public_Database: new ResourceValue('Public Database'),
  Unit_1: new ResourceValue('Unit 1'),
  Router: new ResourceValue('Router'),
  Router_$needle$_Not_Found: new ResourceValue('Router {routerMac} Not Found'),
  Add_Router: new ResourceValue('Add Router'),
  Manage_Routers: new ResourceValue('Manage Routers'),
  Manage_Routers_Description: new ResourceValue('Manage routers that are connected to your app'),
  Routers: new ResourceValue('Routers'),
  Follower_Not_Found: new ResourceValue('Follower \'{followerName}\' Not Found'),
  Search: new ResourceValue('Search'),
  Awesum_Barcode: new ResourceValue('Awesum Barcode'),
  Unknown_app:new ResourceValue('Unknown app'),
  Invalid_email:new ResourceValue('Invalid email'),
  AddFollower: new ResourceValue('AddFollower'),
  Edit_Units:new ResourceValue('Edit Units'),
  Add_Unit_Type:new ResourceValue('Add Unit Type'),
  Add_Database:new ResourceValue('Add Database'),
  Edit_Databases:new ResourceValue('Edit Databases'),
  No_Types:new ResourceValue('No Types'),
  Background_Image:new ResourceValue('Background Image'),
  Image_Preview:new ResourceValue('Image Preview'),
  AppSettings: new ResourceValue('AppSettings'),
  App_Settings: new ResourceValue('App Settings'),
  Delete_Database: new ResourceValue('Delete Database'),
  asc:new ResourceValue('asc'),
  desc:new ResourceValue('desc'),
  number1:new ResourceValue('1'),
  number2:new ResourceValue('2'),
  No_apps_found:new ResourceValue('No apps found, go to '),
  to_edit_apps:new ResourceValue('to create your own app or follow others apps.'),
  Submit:new ResourceValue('Submit'),
  Are_you_sure_you_want_to_totally_delete_everything:new ResourceValue('Are you sure you want to totally delete everything? If so, enter the result of 4 * 10 - 3 + 1'),
  Are_you_sure_you_want_to_totally_delete_everything2:new ResourceValue('Are you sure you want to totally delete everything? If so, enter the result of 4 * 10 - 3 + 1'),
  Delete_All_Data: new ResourceValue('Delete All Data'),
  Local_App: new ResourceValue('Local App'),
  Unique_Name: new ResourceValue('Unique Name'),
  ConfirmOffline: new ResourceValue('ConfirmOffline'),
  Confirm_Offline: new ResourceValue('Confirm Offline'),
  Delete_All_Server_Data: new ResourceValue('Delete All Server Data'),
  Create_App: new ResourceValue('Create App'),
  AddAssignment: new ResourceValue('AddAssignment'),
  Delete_All_Browser_Data: new ResourceValue('Delete All Browser Data'),
  Log_In: new ResourceValue('Log In'),
  Google: new ResourceValue('Google'),
  Choose_A_Login_Provider: new ResourceValue('Choose a login provider below:'),
  Log_Out: new ResourceValue('Log Out'),
  EditJson: new ResourceValue('EditJson'),
  Edit_Json: new ResourceValue('Edit Json'),
  UnitCompleted: new ResourceValue('UnitCompleted'),
  completed: new ResourceValue('completed'),
  SettingsUnit: new ResourceValue('SettingsUnit'),
  
  Unable_To_Connect_To_Server: new ResourceValue('Unable to connect to server'),
  Page_Not_Found: new ResourceValue('Page Not Found'),
  Error: new ResourceValue('Error'),
  Start: new ResourceValue('Begin'),
  Apps: new ResourceValue('Apps'),
  PairedApps: new ResourceValue('Paired Apps'),
  About: new ResourceValue('About'),
  Leaders_And_Followers: new ResourceValue('Leaders And Followers'),
  LeadersAndFollowers: new ResourceValue('LeadersAndFollowers'),
  Leader: new ResourceValue('Leader'),
  Groups: new ResourceValue('Groups'),
  Delete: new ResourceValue('Delete'),
  Add_Reading:new ResourceValue('Add Reading'),
  reading: new ResourceValue('reading'),
  AddSpelling:new ResourceValue('Add Spelling'),
  Database_Not_Found:new ResourceValue('Database not found'),
  Database_$needle$_Not_Found:new ResourceValue('Database {database} not found'),
  Databases:new ResourceValue('Databases'),
  
  DatabaseNotFound:new ResourceValue('DatabaseNotFound'),
  sourcePath: new ResourceValue('sourcePath'),
  sourceQuery: new ResourceValue('sourceQuery'),
  Database_Settings: new ResourceValue('Database Settings'),
  Settings: new ResourceValue('Settings'),
  Unit_Types: new ResourceValue('Unit Types'),
  i: new ResourceValue('i'),
  Add_Follower: new ResourceValue('Add Follower'),
  Add_Leader: new ResourceValue('Add Leader'),
  edit: new ResourceValue('edit'),
  Edit: new ResourceValue('Edit'),
  Areas: new ResourceValue('Areas'),
  Login: new ResourceValue('Login'),
  AWESUM: new ResourceValue('AWESUM'),
  Awesum: new ResourceValue('Awesum'),
  Test: new ResourceValue('Test'),
  Home: new ResourceValue('Home'),
  Show_Units: new ResourceValue('Show Units'),
  Toggle_Fullscreen: new ResourceValue('Toggle Fullscreen'),
  Fullscreen: new ResourceValue('Fullscreen'),
  Spelling_Settings: new ResourceValue('Spelling Settings'),
  Spelling: new ResourceValue('Spelling'),
  spelling: new ResourceValue('spelling'),
  
  OneByTwoDigraphs: new ResourceValue('OneByTwoDigraphs'),
  oneByTwoDigraphs: new ResourceValue('oneByTwoDigraphs'),
  onebytwodigraphs: new ResourceValue('onebytwodigraphs'),
  One_By_Two_Digraphs: new ResourceValue('One By Two Digraphs'),

  OneByOneMultiplication: new ResourceValue('OneByOneMultiplication'),
  oneByOneMultiplication: new ResourceValue('oneByOneMultiplication'),
  onebyonemultiplication: new ResourceValue('onebyonemultiplication'),
  One_By_One_Multiplication: new ResourceValue('One By One Multiplication'),
  Add_One_By_One_Multiplication: new ResourceValue('Add One By One Multiplication'),
  Add_One_By_Two_Digraphs: new ResourceValue('Add One By Two Digraphs'),
  Items: new ResourceValue('Items'),
  Go_To_Spelling_Settings: new ResourceValue('Go To Spelling Settings'),
  Type_Settings: new ResourceValue('Type Settings'),
  homepageImage: new ResourceValue('homepageImage'),
  userName: new ResourceValue('userName'),
  Save: new ResourceValue('Save'),
  Cancel: new ResourceValue('Cancel'),
  Play: new ResourceValue('Play'),
  Refresh: new ResourceValue('Refresh'),
  Name: new ResourceValue('Name'),
  InvalidResponse: new ResourceValue('InvalidResponse'),
  Units: new ResourceValue('Units'),
  Spelling_Item_Settings: new ResourceValue('Spelling Item Settings'),
  OneByTwoDigraphs_Item_Settings: new ResourceValue('One By Two Digraphs Item Settings'),
  Multiplication1x1_Item_Settings: new ResourceValue('Multiplication 1x1 Item Settings'),
  Addition1x1_Item_Settings: new ResourceValue('Addition 1x1 Item Settings'),
  Image: new ResourceValue('Image'),
  Audio: new ResourceValue('Audio'),
  Success_Sound: new ResourceValue('Success Sound'),
  Success_Image: new ResourceValue('Success Image'),
  Success_Animation_Duration: new ResourceValue('Success Animation Duration'),
  Success_Animations: new ResourceValue('Success Animations'),
  Word: new ResourceValue('Word'),
  Digraphs: new ResourceValue('Digraphs'),
  Numbers: new ResourceValue('Numbers'),
  Unit_Settings: new ResourceValue('Unit Settings'),
  Lets_Go: new ResourceValue('Lets Go'),
  Completions: new ResourceValue('Completions'),
  AppCompletions: new ResourceValue('App Completions'),
  DatabaseCompletions: new ResourceValue('Database Completions'),
  Assignments: new ResourceValue('Assignments'),
  Add_Assignment: new ResourceValue('Add Assignment'),
  About_Awesum: new ResourceValue('About Awesum'),
  NameColon: new ResourceValue('Name:'),
  Add_Pairing: new ResourceValue('Add Pairing'),
  Add_Type: new ResourceValue('Add Type'),
  Add_Unit: new ResourceValue('Add Unit'),
  Add_Item: new ResourceValue('Add Item'),
  Must_be_a_valid_MAC_address: new ResourceValue('Must be a valid MAC address'),

  User_Name_Cannot_Be_Blank: new ResourceValue('User Name Cannot Be Blank'),
  You_Must_Be_Logged_In: new ResourceValue('You must be logged in to participate in pairing'),
  No_Error_Found: new ResourceValue('No Error Found'),
  Name_Cannot_Be_Settings: new ResourceValue('Name Cannot Be Settings'),
  Required: new ResourceValue('Required'),
  Must_be_less_than_: new ResourceValue('Must be less than '),
  Must_be_less_than_100: new ResourceValue('Must be less than 100'),
  Cannot_Contain_Slash: new ResourceValue('Cannot contain slash'),
  
  Invalid_Name: new ResourceValue('Invalid name'),
  Unique_Name_must_be_globally_unique: new ResourceValue('Unique name must be globally unique, choose a different name'),
  Unique_Name_cannot_be_api:new ResourceValue('Unique name cannot be "api"'),
  Must_be_valid_email:new ResourceValue('Must be valid email address'),
  Email_does_not_exist:new ResourceValue('Email does not exist'),
  Authentication_Is_Required:new ResourceValue('Authentication is Required'),

  Must_be_a_valid_email:new ResourceValue('Must be a valid email'),
  Must_be_less_than_100_characters:new ResourceValue('Must be less than 200 characters'),
  Must_be_less_than_4000_characters:new ResourceValue('Must be less than 4000 characters'),
  Must_be_less_than_8000_characters:new ResourceValue('Must be less than 8000 characters'),
  Unique_name_contains_reserved_words:new ResourceValue('Unique name contains reserved words'),
  Must_be_less_than_36_characters:new ResourceValue('Must be less than 36 characters'),
  Must_be_less_than_14_characters:new ResourceValue('Must be less than 14 characters'),
  Email_cannot_be_your_email:new ResourceValue('Email cannot be your email'),
  Group_Settings:new ResourceValue('Group Settings'),
  Not_Globally_Unique:new ResourceValue('Not Globally Unique'),
  Must_be_a_valid_UUID:new ResourceValue('Must be a valid UUID'),
  App_Already_Exists:new ResourceValue('App already exists'),
  Unique_name_already_exists:new ResourceValue('Unique name already exists'),
  Unknown_leader_app:new ResourceValue('Unknown leader app'),
  Browser_Storage:new ResourceValue('Browser Storage'),
  Storage_Usage:new ResourceValue('Storage Usage'),
  Storage_Quota:new ResourceValue('Storage Quota'),
  Storage_Used:new ResourceValue('Storage Used'),
  Storage_Free:new ResourceValue('Storage Free'),
  Percent_Used:new ResourceValue('Percent Used'),
  Rename_App:new ResourceValue('Rename App'),
  Error_Resetting_Server_Data:new ResourceValue('Error resetting server data'),
  Not_All_Items_In_Unit_Are_Completed:new ResourceValue('Not all items in the unit are completed'),
  Failed_To_Sync_Completion:new ResourceValue('Failed to sync completion'),
  Monday:new ResourceValue("Monday (Start{'|'}Duration)"),
  Tuesday:new ResourceValue("Tuesday (Start{'|'}Duration)"),
  Wednesday:new ResourceValue("Wednesday (Start{'|'}Duration)"),
  Thursday:new ResourceValue("Thursday (Start{'|'}Duration)"),
  Friday:new ResourceValue("Friday (Start{'|'}Duration)"),
  Saturday:new ResourceValue("Saturday (Start{'|'}Duration)"),
  Sunday:new ResourceValue("Sunday (Start{'|'}Duration)"),
  Must_be_a_valid_time_and_duration:new ResourceValue('Must be a valid time and duration (e.g., 06:30|60)'),
  Log:new ResourceValue('Log'),
  Console_Logs:new ResourceValue('Console Logs'),
  Clear_Logs:new ResourceValue('Clear Logs'),
}


GlobalResources.addKeysToResources(resourcesInternal);
export const resources = resourcesInternal

