/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface AwesumApp {
  authenticationType: string;
  email: string;
  enableNarrator: boolean;
  groups: string;
  homePageImage: string;
  homePageImageType: number;
  id: string;
  lang: string;
  lastModified: number;
  name: string;
  uniqueName: string;
  version: number;
}

export interface AwesumDatabase {
  appId: string;
  homePageIcon: string;
  homePageIconType: number;
  id: string;
  lastModified: number;
  name: string;
  order: number;
  version: number;
}

export interface AwesumDatabaseItem {
  appId: string;
  data: string;
  databaseId: string;
  dataText: string;
  id: string;
  itemType: number;
  lastModified: number;
  order: number;
  unitId: string;
  version: number;
}

export interface AwesumDatabaseUnit {
  appId: string;
  databaseId: string;
  homePageImage: string;
  homePageImageType: number;
  id: string;
  lastModified: number;
  name: string;
  order: number;
  points: number;
  router: string;
  routerTime: number;
  routerTimeImmediate: boolean;
  successAnimations: string;
  successSound: string;
  successSoundType: number;
  successVideoType: number;
  successVideoUrl: string;
  version: number;
}

export interface AwesumDnsEntry {
  domain: string;
  id: string;
  routerId: string;
  timestamp: number;
}

export interface AwesumFollowerDatabase {
  databaseId: string;
  followerRequestId: string;
  id: string;
  lastModified: number;
  version: number;
}

export interface AwesumFollowerDatabaseCompletion {
  description: string;
  followerRequestId: string;
  id: string;
  itemId: string;
  itemLevel: number;
  lastModified: number;
  parentItemId: string;
  version: number;
}

export interface AwesumFollowerRequest {
  followerAppId: string;
  followerEmail: string;
  followerName: string;
  groups: string;
  id: string;
  initiatedByFollower: boolean;
  lastModified: number;
  leaderAppId: string;
  leaderEmail: string;
  leaderName: string;
  points: number;
  status: number;
  version: number;
}

export interface AwesumMedia {
  appId: string;
  data: string;
  id: string;
  lastModified: number;
  size: number;
}

export interface AwesumRouter {
  appId: string;
  fridayTimesAndDurations: string;
  id: string;
  ipAddress: string;
  lastModified: number;
  mondayTimesAndDurations: string;
  routerMac: string;
  saturdayTimesAndDurations: string;
  status: number;
  sundayTimesAndDurations: string;
  thursdayTimesAndDurations: string;
  tuesdayTimesAndDurations: string;
  version: number;
  wednesdayTimesAndDurations: string;
}

export interface DB {
  "awesum.App": AwesumApp;
  "awesum.Database": AwesumDatabase;
  "awesum.DatabaseItem": AwesumDatabaseItem;
  "awesum.DatabaseUnit": AwesumDatabaseUnit;
  "awesum.DnsEntry": AwesumDnsEntry;
  "awesum.FollowerDatabase": AwesumFollowerDatabase;
  "awesum.FollowerDatabaseCompletion": AwesumFollowerDatabaseCompletion;
  "awesum.FollowerRequest": AwesumFollowerRequest;
  "awesum.Media": AwesumMedia;
  "awesum.Router": AwesumRouter;
}
